Repository MIT-Emerging-Talent/ET6-CDSP-group-15-repo, pull requests merged in 2025-06, with the labels that each got.

#3 Add team norms
  collaboration/README.md
Labels: documentation

#6 First draft of the repo's main README
  README.md
Labels: documentation

#2 Constraints
  collaboration/constraints.md
Labels: documentation

#7 Communication update
  collaboration/communication.md
Labels: documentation

#15 Update README.md with correct clone link
  README.md
Labels: documentation

#20 Fixed main README.md linting errors
  README.md
Labels: documentation

#28 Complete Milestone 1 deliverables
  0_domain_study/guide.md
Labels: documentation

#35 Rewriting /0_domian_study/README.md
  0_domain_study/README.md
Labels: documentation

#34 First draft of sources
  0_domain_study/sources/sources.md
Labels: documentation

#41 updated 1_problem_identification.md to resolve #32
  collaboration/retrospectives/1_problem_identification.md
Labels: documentation

#29 Add final questions
  0_domain_study/research_questions/final_questions.md
Labels: documentation, question

#44 Main README - Modified the research question
  README.md
Labels: documentation

#55 Additions of dataset documentation
  1_datasets/README.md
Labels: documentation

#56 cleaned 1_datasets/raw_data/afdr_a8.csv and saved the cleaned version…
  1_datasets/processed_datasets/afdr_cleaned.csv
  2_data_preparation/01_clean_afdr_data.ipynb
  2_data_preparation/02_clean_afdr_charts.ipynb
Labels: coding

#59 Data preparation v3
  .gitignore
  1_datasets/processed_datasets/BNPL_cleaned.csv
  1_datasets/reference/BNPL_intention_to_use_cleaned.csv
  1_datasets/reference/afdr_charts_cleaned.csv
  2_data_preparation/01_clean_afdr_data.ipynb
  2_data_preparation/03_clean_BNPL.ipynb
  2_data_preparation/04_clean_BNPL_intention_to_use.ipynb
Labels: coding

#66 2 data preparation readme update
  2_data_preparation/README.md
Labels: documentation

#62 docs: add first draft of milestone 2 retrospective
  collaboration/retrospectives/2_data_collection.md
Labels: documentation
