Repository MIT-Emerging-Talent/ET6-CDSP-group-15-repo, pull requests merged in 2025-07, with the labels that each got.

#69 Created the visualization and EDA for the processed data
  2_data_preparation/README.md
  3_data_exploration/README.md
  3_data_exploration/afdr_cleaned/explore_afdr_cleaned.ipynb
  3_data_exploration/afdr_cleaned/explore_afdr_cleaned.py
  3_data_exploration/afdr_cleaned/figures/afdr_explored.csv
  3_data_exploration/afdr_cleaned/figures/bnpl_correlation_heatmap.png
  3_data_exploration/afdr_cleaned/figures/bnpl_numeric_distributions.png
  3_data_exploration/bnpl_cleaned/explore_BNPL_cleaned.ipynb
  3_data_exploration/bnpl_cleaned/explore_BNPL_cleaned.py
  3_data_exploration/bnpl_cleaned/figures/BNPL_cleaned_numeric_distributions.png
  3_data_exploration/bnpl_cleaned/figures/bnpl_correlation_heatmap.png
  3_data_exploration/bnpl_cleaned/figures/bnpl_explored.csv
  3_data_exploration/bnpl_cleaned/figures/bnpl_usage_by_indebtedness.png
  3_data_exploration/bnpl_cleaned/figures/financial_stress_by_indebtedness.png
  3_data_exploration/bnpl_intention_to_use_cleaned/explore_BNPL_intention_to_use_cleaned.ipynb
  3_data_exploration/bnpl_intention_to_use_cleaned/explore_BNPL_intention_to_use_cleaned.py
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/AT_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/EE_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/FL_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/IA_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/PA_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/PC_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/PE_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/PR_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/PU_mean_score_dist.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/bnpl_intention_correlation_heatmap.png
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/bnpl_intention_explored.csv
  3_data_exploration/bnpl_intention_to_use_cleaned/figures/likert_first5.png
  3_data_exploration/frbny_sce_credit_access_cleaned/explore_FRBNY_SCE_Credit_Access_cleaned.ipynb
  3_data_exploration/frbny_sce_credit_access_cleaned/explore_FRBNY_SCE_Credit_Access_cleaned.py
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_correlation_heatmap.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_explored.csv
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_auto_loan_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_credit_card_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_home_based_loan_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_mortgage_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_no_credit_products_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_other_personal_loan_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_has_student_loan_distribution.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_numeric_distributions.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_product_ownership.png
  3_data_exploration/frbny_sce_credit_access_cleaned/figures/frbny_respondent_by_month.png
Labels: coding

#77 Added README.md for 1_datasets folder
  1_datasets/README.md
Labels: documentation

#72 Meeting minutes
  collaboration/meeting_minute/6_12_2025.md
  collaboration/meeting_minute/6_14_2025.md
  collaboration/meeting_minute/6_20_2025.md
  collaboration/meeting_minute/6_28_2025.md
  collaboration/meeting_minute/6_2_2025.md
  collaboration/meeting_minute/6_5_2025.md
  collaboration/meeting_minute/6_9_2025.md
  collaboration/meeting_minute/7_4_2025.md
  collaboration/meeting_minute/7_5_2025.md
  collaboration/meeting_minute/7_6_2025.md
Labels: documentation

#94 updated main README to solve #73
  README.md
Labels: documentation, enhancement

#120 Cleaned data prep and clean to solve #117
  2_data_preparation/notebooks/new_notebooks/07_p2p_lending.ipynb
  2_data_preparation/notebooks/old_notebooks/01_clean_afdr_data.ipynb
  2_data_preparation/notebooks/old_notebooks/02_clean_afdr_charts.ipynb
  2_data_preparation/notebooks/old_notebooks/03_clean_BNPL.ipynb
  2_data_preparation/notebooks/old_notebooks/04_clean_BNPL_intention_to_use.ipynb
  2_data_preparation/notebooks/old_notebooks/05_clean_FRBNY-SCE-Credit-Access-complete_microdata.ipynb
  2_data_preparation/notebooks/old_notebooks/07_p2p_lending.ipynb
Labels: Data Cleaning

#121 py version by Dadi
  2_data_preparation/compile_file/p2p_cleaned.py
Labels: documentation

#125 restructure exploration folder
  3_data_exploration/new/README.md
  3_data_exploration/old/afdr_cleaned/explore_afdr_cleaned.ipynb
  3_data_exploration/old/afdr_cleaned/explore_afdr_cleaned.py
  3_data_exploration/old/afdr_cleaned/figures/afdr_explored.csv
  3_data_exploration/old/afdr_cleaned/figures/bnpl_correlation_heatmap.png
  3_data_exploration/old/afdr_cleaned/figures/bnpl_numeric_distributions.png
  3_data_exploration/old/bnpl_cleaned/explore_BNPL_cleaned.ipynb
  3_data_exploration/old/bnpl_cleaned/explore_BNPL_cleaned.py
  3_data_exploration/old/bnpl_cleaned/figures/BNPL_cleaned_numeric_distributions.png
  3_data_exploration/old/bnpl_cleaned/figures/bnpl_correlation_heatmap.png
  3_data_exploration/old/bnpl_cleaned/figures/bnpl_explored.csv
  3_data_exploration/old/bnpl_cleaned/figures/bnpl_usage_by_indebtedness.png
  3_data_exploration/old/bnpl_cleaned/figures/financial_stress_by_indebtedness.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/explore_BNPL_intention_to_use_cleaned.ipynb
  3_data_exploration/old/bnpl_intention_to_use_cleaned/explore_BNPL_intention_to_use_cleaned.py
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/AT_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/EE_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/FL_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/IA_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/PA_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/PC_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/PE_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/PR_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/PU_mean_score_dist.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/bnpl_intention_correlation_heatmap.png
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/bnpl_intention_explored.csv
  3_data_exploration/old/bnpl_intention_to_use_cleaned/figures/likert_first5.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/explore_FRBNY_SCE_Credit_Access_cleaned.ipynb
  3_data_exploration/old/frbny_sce_credit_access_cleaned/explore_FRBNY_SCE_Credit_Access_cleaned.py
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_correlation_heatmap.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_explored.csv
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_auto_loan_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_credit_card_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_home_based_loan_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_mortgage_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_no_credit_products_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_other_personal_loan_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_has_student_loan_distribution.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_numeric_distributions.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_product_ownership.png
  3_data_exploration/old/frbny_sce_credit_access_cleaned/figures/frbny_respondent_by_month.png
Labels: enhancement

#127 restructure / 2_data_preparation
  2_data_preparation/notebooks/new/07_p2p_lending.ipynb
  2_data_preparation/notebooks/new/compile_file/p2p_cleaned.py
  2_data_preparation/notebooks/old/01_clean_afdr_data.ipynb
  2_data_preparation/notebooks/old/02_clean_afdr_charts.ipynb
  2_data_preparation/notebooks/old/03_clean_BNPL.ipynb
  2_data_preparation/notebooks/old/04_clean_BNPL_intention_to_use.ipynb
  2_data_preparation/notebooks/old/05_clean_FRBNY-SCE-Credit-Access-complete_microdata.ipynb
  2_data_preparation/notebooks/old/06_public_2024.ipynb
  2_data_preparation/notebooks/old/07_p2p_lending.ipynb
Labels: enhancement

#134 Refine domain study research questions and documentation
  0_domain_study/README.md
  0_domain_study/research_questions/new/README.md
  0_domain_study/research_questions/new/final_questions.md
  0_domain_study/research_questions/new/initial_questions.md
  0_domain_study/sources/new/README.md
  0_domain_study/sources/new/sources.md
Labels: documentation

#135 quick fixing / touch up / no big changes
  4_data_analysis/07_p2p_lending_(logreg,RF,XGB).ipynb
  4_data_analysis/xgb_model.pkl
Labels: enhancement

#137 final touch up
  4_data_analysis/07_p2p_lending_(logreg,RF,XGB).ipynb
  4_data_analysis/xgb_final_model.pkl
  4_data_analysis/xgb_model.pkl
Labels: enhancement

#145 Drafting retrospective/3_data_analysis and adding individual retrospe…
  collaboration/retrospectives/2_data_collection.md
  collaboration/retrospectives/3_data_analysis.md
Labels: documentation
